In [2]:
import numpy as np

In [6]:
# Outer Products in Python using numpy 
x = np.array([[1],
              [2]])
y = np.array([[2, 3, 4]])
foo = np.outer(x, y)
print(foo)
print(x)
print(y)


[[2 3 4]
 [4 6 8]]
[[1]
 [2]]
[[2 3 4]]
