In [1]:
import numpy as np
import math 
import scipy as sp
from scipy import linalg as LA

In [18]:
# read in the data
x4_data = np.genfromtxt('X4.csv', delimiter=',')
y4_data = np.genfromtxt('y4.csv', delimiter=',')
A_data = np.genfromtxt('A.csv', delimiter=',')

# print the data for debugging

# print("x4 data")
# print(x4_data)
# print("y4 data")
# print(y4_data)
# print("A data")
# print(A_data)


In [54]:
# Question 3

# Compute the SVD
U, s, Vt = LA.svd(A_data)

# print the SVD result
# print(f"U matrix{U}")
# print(f"singular value matrix{s}")
# print(f"V transpose matrix{Vt}")

# Part A
third_singular_value = s[2]
print(f"The third singular value is {third_singular_value}")

# Part B
a_rank = np.linalg.matrix_rank(A_data)
print(f"The rank of a is {a_rank}")

# Part C
aT = A_data.T
aT_a = aT.dot(A_data)
eigenvalues, eigenvectors = np.linalg.eig(aT_a)
print(f"The eigenvalues are {eigenvalues}")
print(f"The eigenvectors are {eigenvectors}")

# Part D
# Source: https://gist.github.com/thearn/

# Calculate the Ak matrix for A2
A2 = np.zeros((len(U), len(Vt)))
# print(A2)
for i in range(2):
    A2 += s[i] * np.outer(U[i], Vt[i])
# print(A2)

# Frobenius Norm
frobenius_norm = math.pow(np.linalg.norm(A_data - A2, 'fro'), 2)
print(f"The frobenius norm squared is {frobenius_norm}")

# Part E
spectral_norm = math.pow(np.linalg.norm(A_data - A2, 1), 2)
print(f"The spectral norm squared is {spectral_norm}")

The third singular value is 0.03942337819653506
The rank of a is 6
The eigenvalues are [9.99906267e-01 3.97685791e-02 1.55420275e-03 6.52894045e-05
 1.70999192e-06 1.95216715e-06]
The eigenvectors are [[ 0.1333662  -0.03940497 -0.15588663  0.37528233  0.86969438  0.24321784]
 [ 0.11437164 -0.40304136  0.48135291  0.00460993  0.25194593 -0.72751506]
 [ 0.37080566  0.86339496  0.1814491  -0.05632106  0.112206   -0.26146945]
 [-0.33023787  0.12406151 -0.70854569  0.18150042  0.01409868 -0.5834154 ]
 [ 0.83982148 -0.2558767  -0.35429924  0.17533217 -0.26517896 -0.0513595 ]
 [ 0.13144801 -0.09843731 -0.28898099 -0.89010454  0.31152221 -0.01375941]]
The frobenius norm squared is 0.47872581602550685
The spectral norm squared is 4.569998350512667


In [ ]:
# Question 2

In [ ]:
# Question 1