In [25]:
import numpy as np
from scipy import linalg

#  Author: Pranav Rajan
# Description: Solves the problems for Question 4 in HW2

# Set up the A and B Matrices
A = np.array([[4, -1, 3], [0, -1, 4], [2, -2, 6]])
B = np.array([[2, 3, -1], [5, 3, 5], [-2, -2, 1]])

# print("The A Matrix\n", A)
# print("The B Matrix\n", B)

# 1) A Transpose multiplied by B
A_Transpose = A.T

Product = np.matmul(A_Transpose, B)
print("Question 4A")
print(Product)

# 2) AB
AB_Product = np.matmul(A, B)
print("Question 4B")
print(AB_Product)

# 3) BA
BA_Product = np.matmul(B, A)
print("Question 4C")
print(BA_Product)

# 4) B + A
BA_Sum = np.add(B, A)
print("Question 4D")
print(BA_Sum)

# Prove that A is an Invertible Matrix
A_Inverse = linalg.inv(A)
print("Question 4E")
print(A_Inverse)
print("Check That A has Inverse")
A_Inverse_Check = A.dot(linalg.inv(A))
print(A_Inverse_Check)

# Prove that B is an Invertible Matrix
B_Inverse = linalg.inv(B)
print("Question 4E")
print(B_Inverse)
print("Check that B has Inverse")
B_Inverse_Check = B.dot(linalg.inv(B))
print(B_Inverse_Check)




Question 4A
[[ 4  8 -2]
 [-3 -2 -6]
 [14  9 23]]
Question 4B
[[ -3   3  -6]
 [-13 -11  -1]
 [-18 -12  -6]]
Question 4C
[[  6  -3  12]
 [ 30 -18  57]
 [ -6   2  -8]]
Question 4D
[[ 6  2  2]
 [ 5  2  9]
 [ 0 -4  7]]
Question 4E
[[ 0.33333333 -0.         -0.16666667]
 [ 1.33333333  3.         -2.66666667]
 [ 0.33333333  1.         -0.66666667]]
Check That A has Inverse
[[ 1.00000000e+00  0.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]
Question 4E
[[-0.86666667  0.06666667 -1.2       ]
 [ 1.          0.          1.        ]
 [ 0.26666667  0.13333333  0.6       ]]
Check that B has Inverse
[[ 1.00000000e+00  8.32667268e-17  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  2.22044605e-16]
 [-5.55111512e-17 -8.32667268e-17  1.00000000e+00]]
